services:
  - type: web
    name: storefront-api
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: node dist/infrastructure/web/server.js
    envVars:
      - key: PORT
        value: 3000
      - key: AUTH_SERVICE_URL
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: defaultdb
      - key: DB_PORT
        value: 3306
      - key: JWT_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
